#train
audio_csv_train: AudioCaps_csv/train.csv 
rir_csv_train:   RIR_dataset/rir_catalog_train.csv
stats_path: RIR_dataset/stats_new.pt

# val
audio_csv_val: val_fixed_96x96/audio_fixed.csv      # 省略可
rir_csv_val: val_fixed_96x96/rir_fixed.csv        # 省略可


# test
audio_csv_test: test_fixed_96x96/audio_fixed.csv      # 省略可
rir_csv_test: test_fixed_96x96/rir_fixed.csv        # 省略可
out_dir: /home/takamichi-lab-pc09/DELSA/Spatial_AudioCaps/takamichi09/for_delsa_spatialAudio_test 
#予め作っておく クラスタ分散とMIG用
SpatialAudio_csv_val: /home/takamichi-lab-pc09/DELSA/Spatial_AudioCaps/takamichi09/for_delsa_spatialAudio 

# 前計算Valの場所（precompute_val.py の out_dir）
val_precomp_root: Spatial_AudioCaps/takamichi09/for_delsa_spatialAudio_val
val_index_csv:    Spatial_AudioCaps/takamichi09/for_delsa_spatialAudio_val/val_precomputed.csv   # 省略可（rootからの既定を使う）

test_precomp_root: Spatial_AudioCaps/takamichi09/for_delsa_spatialAudio_test
test_index_csv:    Spatial_AudioCaps/takamichi09/for_delsa_spatialAudio_test/test_precomputed.csv   # 省略可（rootからの既定を使う）

val_dry_per_batch: 24
val_rirs_per_batch: 3

exclude_diag: True  
use_amp: True
audio_base: AudioCaps_mp3 
batch_size: 24
n_views: 3
val_n_views: 96
epochs: 40
lr: 0.00005
device: auto            # "auto" → cuda if available
wandb: true
proj: delsa-sup-contrast
run_name: 8/17 3:58
# 追加
audio_base_pcm: AudioCaps_pcm48k # ← 上の out-root を指定
prefer_pcm: true # ← wav があれば優先

# baseline_ckpt_path: Spatial_AudioCaps/takamichi09/elsa_ckck_0711/elsa_epoch_30.pt
# freeze_backbones_if_baseline_loaded: true

wandb_id: 50topfkq     # 既存runのID（重要）
resume_ckpt: Spatial_AudioCaps/takamichi09/checkpoints_delsa/ckpt_sup_ep9.pt
ckpt_dir: Spatial_AudioCaps/takamichi09/checkpoints_delsa
save_every: 1              # 何エポックごとに保存するか
#epochs: 20                 # 「最終到達エポック」を指定（例：20まで回す）
