_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
audio_base:
    value: AudioCaps_mp3
audio_csv:
    value: AudioCaps_csv/train.csv
batch_size:
    value: 8
device:
    value: cpu
epochs:
    value: 5
lr:
    value: 0.0001
n_views:
    value: 4
proj:
    value: delsa-sup-contrast
rir_csv:
    value: RIR_dataset/rir_catalog_train.csv
run_name:
    value: null
split:
    value: train
wandb:
    value: true
